// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrqpgwragrytxwlyamtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndycXBnd3JhZ3J5dHh3bHlhbXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NzM1NDgsImV4cCI6MjA3MzE0OTU0OH0.NoKuc_2pOfSP8c9ZBrtu96uxmy1h8u8eHFLvodJtvUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});